---
- name: Run modules.py
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    project_root: "../"
    error_code: null
    error_detail: null
    error_log: null
    cmdb_url: http://10.100.1.134/
    dcmdb_token: 4|bVIJoyVO94y6agoON6VY0JQ0rJ0Qg7wnsxBfBPRV310bff0c
    url_mutate: http://10.100.1.134/api/cms/assets/softwares/mutate
    url_search: http://10.100.1.134/api/cms/assets/softwares/search
    url_delete: http://10.100.1.134/api/cms/assets/softwares
    # dcmdb_token: 1|twygbIP3K48gkeLm0t8D5ILbdg08Kh9AbK8lTK9509bf676c
    # url_mutate: http://localhost/api/cms/assets/softwares/mutate
    # url_search: http://localhost/api/cms/assets/softwares/search
    # url_delete: http://localhost/api/cms/assets/softwares
  vars_files:
    - "{{ project_root }}/vars/assets_test.yml"
    # - "{{ project_root }}/vars/dcmdb_api.yml"

  tasks:

    - name: Validate token
      block:

        - name: Validation token
          ansible.builtin.assert:
            that:
              - dcmdb_token is defined
              - dcmdb_token != ''
            fail_msg: "El token no está definido en el archivo de configuración."
            success_msg: "Token validado, token={{ dcmdb_token }}"
      rescue:
        - name: Setter errors model
          ansible.builtin.set_fact:
            error_code: "El token no está definido en el archivo de configuración."
            error_detail: "El token no está definido en el archivo de configuración."
            error_log: "El token no está definido en el archivo de configuración."

        - name: Debug in model
          ansible.builtin.fail:
            msg: "{{ error_log }}"
          when: error_log is defined

    - name: Insertar datos
      block:
        - name: Módulo mutate
          mutate:
            url: "{{ url_mutate }}"
            batch_size: 10
            token: "{{ dcmdb_token }}"
            operations: "{{ asset_mutation }}"
          register: response

        - name: Debug response
          ansible.builtin.debug:
            var: response

      rescue:
        - name: Rescue insertion data
          ansible.builtin.fail:
            msg: "{{ error_log }}"
          when: error_log is defined 

    - name: Recuperar datos
      block:
        - name: Módulo search
          search:
            url:  "{{ url_search }}"
            token: "{{ dcmdb_token }}"
            search_params:
              selects:
              - field: "id"
              - field: "name"
              - field: "code"
              includes:
                - relation: "publisher"
                  type: "max"
                  field: "id"
              limit: 10
          register: response

        - name: Debug response
          ansible.builtin.debug:
            var: response

        - name: Extraer lista de IDs
          set_fact:
            operations: "{{ response.data | map(attribute='id') | list }}"

        - name: Mostrar lista de IDs
          debug:
            var: module_ids

      rescue:
        - name: Rescue insertion data
          ansible.builtin.fail:
            msg: "{{ error_log }}"
          when: error_log is defined 

    - name: Eliminar datos
      block:
        - name: Módulo delete
          delete:
            url:  "{{ url_delete }}"
            batch_size: 10
            token: "{{ dcmdb_token }}"
            operations: "{{ operations }}"
          register: response

        - name: Debug response
          ansible.builtin.debug:
            var: response

      rescue:
        - name: Rescue insertion data
          ansible.builtin.fail:
            msg: "{{ error_log }}"
          when: error_log is defined 